Numpy- Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

ndarray- An array class in Numpy is called as ndarray.It is an N-dimensional array.Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

Creating ndarray

In [2]:
import numpy as np
arr=np.array([[1,3,4],[4,6,7]])
type(arr)


numpy.ndarray

Data types in Numpy.

Every ndarray has an associated data type (dtype) object. This data type object (dtype) provides information about the layout of the array. 

In [3]:
arr.dtype

dtype('int32')

In Numpy, datatypes of Arrays need not to be defined unless a specific datatype is required. Numpy tries to guess the datatype for Arrays which are not predefined in the constructor function.

In [5]:
import numpy as np
x=np.array([1,2])
print("Integer datatype: ")
print(x.dtype)

Integer datatype: 
int32


Arithmetic with numpy array

In Numpy arrays, basic mathematical operations are performed element-wise on the array

In [6]:
x=np.array([2,4])
y=np.array([3,5])

In [7]:
w=x+y
#Addition

In [8]:
print(w)

[5 9]


In [9]:
v=x-y
#Substraction

In [10]:
print(v)

[-1 -1]


Basic Indexing and Slicing

Slicing: Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

Indexing: In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

In [11]:
print(arr)

[[1 3 4]
 [4 6 7]]


In [14]:
print(arr[:2,:2])

[[1 3]
 [4 6]]


In [16]:
arr[0,1]=6
print(arr)

[[1 6 4]
 [4 6 7]]


Useful Function of Numpy array

In [17]:
arr.dtype

dtype('int32')

In [19]:
arr.size

6

In [21]:
arr.max()

7

In [22]:
np.sqrt(arr)

array([[1.        , 2.44948974, 2.        ],
       [2.        , 2.44948974, 2.64575131]])

In [23]:
arr.sum()

28

In [24]:
arr.shape

(2, 3)